# Generated by Django 5.0.4 on 2024-04-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_userprofile_password_alter_userprofile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='нету пароля', max_length=128),
        ),
    ]
